// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Db_Operations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219102120_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Department", b =>
                {
                    b.Property<int>("DeptNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DEPTNO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptNo"));

                    b.Property<string>("DName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DNAME");

                    b.Property<string>("Loc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LOC");

                    b.HasKey("DeptNo");

                    b.ToTable("dept", (string)null);
                });

            modelBuilder.Entity("Employee", b =>
                {
                    b.Property<int>("EmpNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EMPNO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpNo"));

                    b.Property<decimal?>("Comm")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("COMM");

                    b.Property<int>("DeptNo")
                        .HasColumnType("int")
                        .HasColumnName("DEPTNO");

                    b.Property<string>("EName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ENAME");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("HIREDATE");

                    b.Property<string>("Job")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JOB");

                    b.Property<int?>("Mgr")
                        .HasColumnType("int")
                        .HasColumnName("MGR");

                    b.Property<decimal>("Sal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SAL");

                    b.HasKey("EmpNo");

                    b.HasIndex("DeptNo");

                    b.ToTable("emp", (string)null);
                });

            modelBuilder.Entity("Employee", b =>
                {
                    b.HasOne("Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DeptNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
